version: '3.4'

services:
  api:
    container_name: api
    expose:
      - 80
    build:
      context: .
      dockerfile: ./Web.Api/Dockerfile
    environment: 
      - TZ=Australia/Melbourne
      - USER_SECRETS_ID=193656b1-3cdc-49cf-9158-8539ca569208
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  spa:
    container_name: spa
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: ./Web.Spa/Dockerfile

  mongo:
    container_name: mongodb
    image: mongo:latest
    # command: [--auth]
    ports:
      - "27017:27017"